In [1]:
!python --version

Python 3.11.11


In [2]:
import torch

In [3]:
torch.version.__version__

'2.5.1+cu124'

### 3.2.1 从 Python 列表到 PyTorch 张量

In [4]:
# 从 Python 列表到 PyTorch 张量
a = [1.0, 2.0, 1.0]

In [5]:
a[0]

1.0

In [6]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

### 3.2.2 构造第 1 个张量

In [7]:
import torch  # 导入 torch 模块

a = torch.ones(3)  # 创建一个大小为 3 的一维张量, 用 1.0 填充
a

tensor([1., 1., 1.])

In [8]:
a[1]

tensor(1.)

In [9]:
float(a[1])

1.0

In [10]:
a[2] = 2.0
a

tensor([1., 1., 2.])

### 3.2.3 张量的本质

In [11]:
# 假设我们有一个坐标列表, 我们想用它来表示一个几何对象: 如一个二维三角形, 顶点坐标为 (4, 1)、(5, 3) 和 (2, 1).
# 这个例子与深度学习并不是特别相关, 但很容易理解.
# 我们可以使用一维张量, 将 x 轴坐标存储在偶数索引中, 将 y 轴坐标存储在奇数索引中, 如下所示:
points = torch.zeros(6)  # 使用 zeros() 函数只是获得适当大小的数组的一种方法
points[0] = 4.0  # 我们用我们真正想要的值来覆盖这些 0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [12]:
# 我们还可以向构造函数传递一个 Python 列表达到同样的效果, 如下所示:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [14]:
# 向构造函数传递了一个元素为列表的列表
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
# 查看张量的形状
points.shape

torch.Size([3, 2])

In [16]:
# 查看张量的维数
points.dim()

2

In [17]:
# 使用 zeros()或 ones() 函数来初始化张量, 以元组的形式来指定大小
points = torch.zeros((3, 2))
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [19]:
# 用 2 个索引来访问张量中的单个元素
points[0, 1]

tensor(1.)

In [20]:
points[0]

tensor([4., 1.])

## 3.3 索引张量

In [21]:
# 范围索引表示法
some_list = list(range(6))
some_list[:]  # 列表中所有元素
some_list[1:4]  # 包含第 1 个元素到第 3 个元素, 不包含第 4 个元素
some_list[1:]  # 包含第 1 个元素到列表末尾的元素
some_list[:4]  # 从列表开始到第 3 个元素, 不包含第 4 个元素
some_list[:-1]  # 从列表的开始到最后一个元素之前的所有元素
some_list[1:4:2]  # 从第 1 个元素(包含)到第 4 个元素(不包含), 移动步长为 2

[1, 3]

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points[1:]  # 第 1 行之后的所有行, 隐含所有列
points[1:, :]  # 第 1 行之后的所有行, 所有列
points[1:, 0]  # 第 1 行之后的所有行, 第 1 列
points[None]  # 增加大小为 1 的维度, 就像 unsqueeze() 方法一样

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

### 3.5.3 管理张量的 dtype 属性

In [23]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [24]:
short_points.dtype

torch.int16

In [25]:
# 使用相应的转换方法将张量创建函数的输出转换为正确的类型
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [26]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [27]:
points_64 = torch.rand(
    5, dtype=torch.double
)  # rand() 方法将张量元素初始化为 0~1 的随机数  64-bit floating point
points_short = points_64.to(torch.short)  # 16-bit integer (signed)
points_64 * points_short  # 从 PyTorch 1.3 起工作

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## 3.6 张量的 API

In [28]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [29]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### 3.7.1 索引存储区

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

<ipython-input-30-8575ff47c9e0>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [31]:
points.untyped_storage()

 0
 0
 128
 64
 0
 0
 128
 63
 0
 0
 160
 64
 0
 0
 64
 64
 0
 0
 0
 64
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cpu) of size 24]

In [32]:
# 索引存储区
points_storage = points.storage()
points_storage[0]

4.0

In [33]:
points.storage()[1]

1.0

In [34]:
# 我们不能用 2 个索引来索引二维张量的存储区. 不管和存储区关联的任何其他张量的维度是多少, 它的布局始终是一维的.
# 从这点来说, 改变一个存储区的值导致与其关联的张量的内容发生变化就不足为怪了
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

### 3.7.2 修改存储值: 就地操作

In [35]:
a = torch.ones(3, 2)

In [36]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### 3.8.1 另一个张量的存储视图

In [37]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [38]:
second_point.size()

torch.Size([2])

In [39]:
second_point.shape

torch.Size([2])

In [40]:
# 步长是一个元组, 指示当索引在每个维度中增加 1 时在存储区中必须跳过的元素数量
points.stride()

(2, 1)

In [41]:
# 当我们索引一个特定的点, 同时看到偏移量增加时, 表明我们已经提取了一个子张量, 让我们看看大小和步长发生了什么变化
second_point = points[1]
second_point.size()

torch.Size([2])

In [42]:
second_point.storage_offset()

2

In [43]:
second_point.stride()

(1,)

In [44]:
# 正如我们预期的那样, 子张量的维度少了一维, 同时仍然索引了与原始张量 points 相同的存储区.
# 这也意味着更改子张量会对原始张量产生影响
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [45]:
# 这可能并不总是可取的, 因此我们最终可以把这个子张量复制成一个新的张量
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### 3.8.2 无复制转置

In [46]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [47]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [48]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
id(points.storage()) == id(points_t.storage())

True

In [49]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
id(points.untyped_storage()) == id(points.untyped_storage())

True

In [50]:
points.stride()

(2, 1)

In [51]:
points_t.stride()

(1, 2)

### 3.8.3 高维转置

In [52]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [53]:
transpose_t.shape

torch.Size([5, 4, 3])

In [54]:
some_t.stride()

(20, 5, 1)

In [55]:
transpose_t.stride()

(1, 5, 20)

### 3.8.4 连续张量

在 PyTorch 中一些张量操作只对连续张量起作用, 如我们在第 4 章中要遇到的 `view()` 方法.

在这种情况下, PyTorch 将抛出一个提供有用信息的异常, 并要求我们显式地调用 `contiguous()` 方法.

值得注意的是, 如果张量已经是连续的, 那么调用 contiguous() 方法不会产生任何操作, 也不会影响性能.

在示例中, 张量 points 是连续的, 然而它的转置却不是

In [56]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points.is_contiguous()

True

In [57]:
points_t.is_contiguous()

False

In [58]:
# 利用 contiguous() 方法, 我们可以通过一个非连续张量得到一个新的连续张量.
# 张量的内容是一样的, 但是步长和存储发生了改变.
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [59]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [60]:
points_t.stride()

(1, 2)

In [61]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [62]:
points_t_cont.stride()

(3, 1)

In [63]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

## 3.9 将张量存储到 GPU

In [64]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device="cuda")

In [65]:
points_gpu = points.to(device="cuda")

In [66]:
# 如果我们的机器有多个 GPU, 我们也可以通过从 0 开始传递一个整数来确定存储张量的 GPU
points_gpu = points.to(device="cuda:0")

In [67]:
points = 2 * points  # 在 CPU 上执行乘法
points_gpu = 2 * points.to(device="cuda")  # 在 GPU 上执行乘法

In [68]:
# 加法仍然在 GPU 上执行, 没有信息流到 CPU, 除非我们输出或访问得到的张量.
# 为了将张量移回 CPU, 我们需要向 to() 方法提供一个 cpu 参数
points_gpu = points_gpu + 4

In [69]:
points_cpu = points_gpu.to(device="cpu")

In [70]:
# 我们也可以使用简写的 cpu() 和 cuda() 方法来代替 to() 方法实现相同的目标
# GPU 索引默认为 0
# 还值得一提的是, 通过使用 to() 方法, 我们可以同时通过 device 和 dtype 参数来更改位置和 据类型
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

## 3.10 NumPy 互操作性

In [71]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [72]:
points = torch.from_numpy(points_np)

## 3.12 序列化张量

In [73]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

# torch.save(points, "../data/p1ch3/ourpoints.t")
torch.save(points, "./data/p1ch3/ourpoints.t")

In [74]:
# with open("../data/p1ch3/ourpoints.t", "wb") as f:
with open("./data/p1ch3/ourpoints.t", "wb") as f:
    torch.save(points, f)

In [75]:
# points = torch.load("../data/p1ch3/ourpoints.t")
points = torch.load("./data/p1ch3/ourpoints.t")
points

<ipython-input-75-18804877cabb>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load("./data/p1ch3/ourpoints.t")


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [76]:
# with open("../data/p1ch3/ourpoints.t", "rb") as f:
with open("./data/p1ch3/ourpoints.t", "rb") as f:
    points = torch.load(f)
points

<ipython-input-76-41d4b630bdb2>:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load(f)


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### 用 h5py 序列化到 HDF5

In [77]:
import h5py

points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

# 我们将张量 points 转换为一个 NumPy 数组(如前所述, 这不会带来开销), 同时将其传递给 create_dataset() 函数
# f = h5py.File("../data/p1ch3/ourpoints.hdf5", "w")
f = h5py.File("./data/p1ch3/ourpoints.hdf5", "w")
dset = f.create_dataset("coords", data=points.numpy())
f.close()

In [78]:
# 这里的 "coords" 是保存到 HDF5 文件的一个键, 我们可以有其他键, 甚至可以嵌套键.
# HDF5 中有趣的事情之一是我们可以在磁盘上索引数据集, 并只访问我们感兴趣的元素.
# 假设我们只想加载数据集中的最后 2 个点

# f = h5py.File("../data/p1ch3/ourpoints.hdf5", "r")
f = h5py.File("./data/p1ch3/ourpoints.hdf5", "r")
dset = f["coords"]
last_points = dset[-2:]
last_points

array([[5., 3.],
       [2., 1.]], dtype=float32)

In [79]:
# 当进行打开文件或需要数据集对象操作时, 不会加载数据.
# 更确切地说, 在我们请求数据集中第 2 行到最后一行数据之前, 数据一直保存在磁盘上.
# 此时 h5py 访问这两列并返回一个类似 NumPy 数组的对象, 该对象将所访问的区域封装在数据集中, 其行为类似于 NumPy 数组, 并与其具有相同的 API.
# 因此我们要将返回的对象传递给 torch.from_numpy() 函数直接获得张量
# 注意, 在这种情况下, 数据会被复制到张量所在的存储中
last_points = torch.from_numpy(dset[-2:])
f.close()
last_points

tensor([[5., 3.],
        [2., 1.]])