In [63]:
!python --version

Python 3.11.11


In [64]:
import torch

In [65]:
torch.version.__version__

'2.5.1+cu124'

In [66]:
a = [1.0, 2.0, 1.0]

In [67]:
a[0]

1.0

In [68]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [69]:
import torch  # <1>

a = torch.ones(3)  # <2>
a

tensor([1., 1., 1.])

In [70]:
a[1]

tensor(1.)

In [71]:
float(a[1])

1.0

In [72]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [73]:
points = torch.zeros(6)  # <1>
points[0] = 4.0  # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [74]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [75]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [76]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [77]:
points.shape

torch.Size([3, 2])

In [78]:
points.dim()

2

In [79]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [80]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [81]:
points[0, 1]

tensor(1.)

In [82]:
points[0]

tensor([4., 1.])

In [83]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [84]:
points.untyped_storage()

 0
 0
 128
 64
 0
 0
 128
 63
 0
 0
 160
 64
 0
 0
 64
 64
 0
 0
 0
 64
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cpu) of size 24]

In [85]:
points_storage = points.storage()
points_storage[0]

4.0

In [86]:
points.storage()[1]

1.0

In [87]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [88]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [89]:
second_point.size()

torch.Size([2])

In [90]:
second_point.shape

torch.Size([2])

In [91]:
points.stride()

(2, 1)

In [92]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [93]:
second_point.storage_offset()

2

In [94]:
second_point.stride()

(1,)

In [95]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [96]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [97]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [98]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [99]:
id(points.storage()) == id(points_t.storage())

False

In [100]:
points.stride()

(2, 1)

In [101]:
points_t.stride()

(1, 2)

In [102]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [103]:
transpose_t.shape

torch.Size([5, 4, 3])

In [104]:
some_t.stride()

(20, 5, 1)

In [105]:
transpose_t.stride()

(1, 5, 20)

In [106]:
points.is_contiguous()

True

In [107]:
points_t.is_contiguous()

False

In [108]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [109]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [110]:
points_t.stride()

(1, 2)

In [111]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [112]:
points_t_cont.stride()

(3, 1)

In [113]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [114]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [115]:
short_points.dtype

torch.int16

In [116]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [117]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [118]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [119]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [120]:
some_list = list(range(6))
some_list[:]  # <1>
some_list[1:4]  # <2>
some_list[1:]  # <3>
some_list[:4]  # <4>
some_list[:-1]  # <5>
some_list[1:4:2]  # <6>

[1, 3]

In [121]:
points[1:]  # <1>
points[1:, :]  # <2>
points[1:, 0]  # <3>
points[None]  # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [122]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [123]:
points = torch.from_numpy(points_np)

In [124]:
# torch.save(points, "../data/p1ch3/ourpoints.t")
torch.save(points, "./data/p1ch3/ourpoints.t")

In [125]:
# with open("../data/p1ch3/ourpoints.t", "wb") as f:
with open("./data/p1ch3/ourpoints.t", "wb") as f:
    torch.save(points, f)

In [126]:
# points = torch.load("../data/p1ch3/ourpoints.t")
points = torch.load("./data/p1ch3/ourpoints.t")

<ipython-input-126-e3e24b120636>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load("./data/p1ch3/ourpoints.t")


In [127]:
# with open("../data/p1ch3/ourpoints.t", "rb") as f:
with open("./data/p1ch3/ourpoints.t", "rb") as f:
    points = torch.load(f)

<ipython-input-127-ffd84cc9812d>:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  points = torch.load(f)


In [128]:
import h5py

# f = h5py.File("../data/p1ch3/ourpoints.hdf5", "w")
f = h5py.File("./data/p1ch3/ourpoints.hdf5", "w")
dset = f.create_dataset("coords", data=points.numpy())
f.close()

In [129]:
# f = h5py.File("../data/p1ch3/ourpoints.hdf5", "r")
f = h5py.File("./data/p1ch3/ourpoints.hdf5", "r")
dset = f["coords"]
last_points = dset[-2:]

In [130]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [131]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device="cuda")

In [132]:
points_gpu = points.to(device="cuda")

In [133]:
points_gpu = points.to(device="cuda:0")

In [134]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device="cuda")  # <2>

In [135]:
points_gpu = points_gpu + 4

In [136]:
points_cpu = points_gpu.to(device="cpu")

In [137]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [138]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [139]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [140]:
a = torch.ones(3, 2)

In [141]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])