In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
import numpy as np
import collections

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.set_printoptions(edgeitems=2)
torch.manual_seed(123)

## nn.Linear

In [2]:
model = nn.Linear(3, 4)

print("model:", model)
print("---" * 3)

# for p in model.parameters():
for p in model.named_parameters():
    print("p:", p)

print("---" * 3)

print("model.weight:", model.weight)
print("model.weight.shape:", model.weight.shape)
print("model.weight.numel:", model.weight.numel())
print("model.weight.dtype:", model.weight.dtype)
print("model.weight.device:", model.weight.device)

print("model.bias:", model.bias)
print("model.bias.shape:", model.bias.shape)
print("model.bias.numel:", model.bias.numel())
print("model.bias.dtype:", model.bias.dtype)
print("model.bias.device:", model.bias.device)

model: Linear(in_features=3, out_features=4, bias=True)
---------
p: ('weight', Parameter containing:
tensor([[-0.2354,  0.0191, -0.2867],
        [ 0.2177, -0.4919,  0.4232],
        [-0.4196, -0.4590, -0.3648],
        [ 0.2615, -0.2133,  0.2161]], requires_grad=True))
p: ('bias', Parameter containing:
tensor([-0.4900, -0.3503, -0.2120, -0.1135], requires_grad=True))
---------
model.weight: Parameter containing:
tensor([[-0.2354,  0.0191, -0.2867],
        [ 0.2177, -0.4919,  0.4232],
        [-0.4196, -0.4590, -0.3648],
        [ 0.2615, -0.2133,  0.2161]], requires_grad=True)
model.weight.shape: torch.Size([4, 3])
model.weight.numel: 12
model.weight.dtype: torch.float32
model.weight.device: cpu
model.bias: Parameter containing:
tensor([-0.4900, -0.3503, -0.2120, -0.1135], requires_grad=True)
model.bias.shape: torch.Size([4])
model.bias.numel: 4
model.bias.dtype: torch.float32
model.bias.device: cpu


In [3]:
input = torch.randn(2, 3)
print("input:", input)
print("input.shape:", input.shape)

input: tensor([[ 0.3239, -0.1085,  0.2103],
        [-0.3908,  0.2350,  0.6653]])
input.shape: torch.Size([2, 3])


In [4]:
output = model(input)  # [2, 3] * [3, 4] + [4] 有矩阵装置操作
print("output:", input)
print("output.shape:", output.shape)

output: tensor([[ 0.3239, -0.1085,  0.2103],
        [-0.3908,  0.2350,  0.6653]])
output.shape: torch.Size([2, 4])


## nn.Tanh

In [5]:
model = nn.Tanh()

print("model:", model)
print("---" * 3)

# for p in model.parameters():
for p in model.named_parameters():
    print("p:", p)

print("---" * 3)

# print("model.weight:", model.weight)
# print("model.weight.shape:", model.weight.shape)
# print("model.weight.numel:", model.weight.numel())
# print("model.weight.dtype:", model.weight.dtype)
# print("model.weight.device:", model.weight.device)

# print("model.bias:", model.bias)
# print("model.bias.shape:", model.bias.shape)
# print("model.bias.numel:", model.bias.numel())
# print("model.bias.dtype:", model.bias.dtype)
# print("model.bias.device:", model.bias.device)

model: Tanh()
---------
---------


In [6]:
input = torch.randn(2, 3)
print("input:", input)
print("input.shape:", input.shape)

input: tensor([[ 0.3528,  0.9728, -0.0386],
        [-0.8861, -0.4709, -0.4269]])
input.shape: torch.Size([2, 3])


In [7]:
output = model(input)
print("output:", input)
print("output.shape:", output.shape)

output: tensor([[ 0.3528,  0.9728, -0.0386],
        [-0.8861, -0.4709, -0.4269]])
output.shape: torch.Size([2, 3])


## nn.Conv2d

In [8]:
model = nn.Conv2d(6, 8, kernel_size=2)

print("model:", model)
print("---" * 3)

# for p in model.parameters():
for p in model.named_parameters():
    print("p:", p)

print("---" * 3)

# print("model.weight:", model.weight)
print("model.weight.shape:", model.weight.shape)
print("model.weight.numel:", model.weight.numel())
print("model.weight.dtype:", model.weight.dtype)
print("model.weight.device:", model.weight.device)

# print("model.bias:", model.bias)
print("model.bias.shape:", model.bias.shape)
print("model.bias.numel:", model.bias.numel())
print("model.bias.dtype:", model.bias.dtype)
print("model.bias.device:", model.bias.device)

model: Conv2d(6, 8, kernel_size=(2, 2), stride=(1, 1))
---------
p: ('weight', Parameter containing:
tensor([[[[-0.0381, -0.1095],
          [-0.0186,  0.1934]],

         [[-0.0161,  0.0065],
          [-0.0318,  0.0321]],

         [[ 0.1819,  0.1248],
          [ 0.0725,  0.0444]],

         [[ 0.0481,  0.0789],
          [-0.0264, -0.1897]],

         [[-0.1262,  0.1742],
          [ 0.0122, -0.1654]],

         [[ 0.0322,  0.1687],
          [-0.1929, -0.1374]]],


        [[[-0.0813,  0.0082],
          [-0.0476, -0.0224]],

         [[-0.1990,  0.0956],
          [ 0.1792,  0.1248]],

         [[-0.1445, -0.1645],
          [ 0.0848,  0.0046]],

         [[ 0.0837, -0.1995],
          [-0.0122,  0.1440]],

         [[ 0.0947,  0.0075],
          [ 0.0401, -0.0193]],

         [[-0.1122, -0.0771],
          [-0.1243,  0.1695]]],


        [[[ 0.1123,  0.0714],
          [-0.1565,  0.1575]],

         [[ 0.0640,  0.1412],
          [-0.0803,  0.0433]],

         [[ 0.1993,  0.1373

In [9]:
input = torch.randn(2, 6, 4, 4)
print("input:", input)
print("input.shape:", input.shape)

input: tensor([[[[ 1.3113, -0.0360,  0.2118, -0.0086],
          [ 1.8576,  2.1321, -0.5056, -0.7988],
          [-1.0944, -1.0197, -0.5399,  1.2117],
          [-0.8632,  1.3337,  0.0771, -0.0522]],

         [[ 0.2386,  0.1411, -1.3354, -2.9340],
          [ 0.1141, -1.2072, -0.3008,  0.1427],
          [-1.3027, -0.4919, -2.1429,  0.9488],
          [-0.5684, -0.0646,  0.6647, -2.7836]],

         [[ 1.1366,  0.9089,  0.9494,  0.0266],
          [-0.9221,  0.7034, -0.3659, -0.1965],
          [-0.9207,  0.3154, -0.0217,  0.3441],
          [ 0.2271, -0.4597, -0.6183,  0.2461]],

         [[-0.4055, -0.8368,  1.2277, -0.4297],
          [-2.2121, -0.3780,  0.9838, -1.0895],
          [ 0.2017,  0.0221, -1.7753, -0.7490],
          [ 0.2781, -0.9621, -0.4223, -1.1036]],

         [[ 0.2473,  1.4549, -0.2835, -0.3767],
          [-0.0306, -0.0894, -0.1965, -0.9713],
          [ 0.9005, -0.2523,  1.0669, -0.2985],
          [ 0.8558,  1.6098, -1.1893,  1.1677]],

         [[ 0.3277, -0.

In [10]:
output = model(input)
print("output:", input)
print("output.shape:", output.shape)

output: tensor([[[[ 1.3113, -0.0360,  0.2118, -0.0086],
          [ 1.8576,  2.1321, -0.5056, -0.7988],
          [-1.0944, -1.0197, -0.5399,  1.2117],
          [-0.8632,  1.3337,  0.0771, -0.0522]],

         [[ 0.2386,  0.1411, -1.3354, -2.9340],
          [ 0.1141, -1.2072, -0.3008,  0.1427],
          [-1.3027, -0.4919, -2.1429,  0.9488],
          [-0.5684, -0.0646,  0.6647, -2.7836]],

         [[ 1.1366,  0.9089,  0.9494,  0.0266],
          [-0.9221,  0.7034, -0.3659, -0.1965],
          [-0.9207,  0.3154, -0.0217,  0.3441],
          [ 0.2271, -0.4597, -0.6183,  0.2461]],

         [[-0.4055, -0.8368,  1.2277, -0.4297],
          [-2.2121, -0.3780,  0.9838, -1.0895],
          [ 0.2017,  0.0221, -1.7753, -0.7490],
          [ 0.2781, -0.9621, -0.4223, -1.1036]],

         [[ 0.2473,  1.4549, -0.2835, -0.3767],
          [-0.0306, -0.0894, -0.1965, -0.9713],
          [ 0.9005, -0.2523,  1.0669, -0.2985],
          [ 0.8558,  1.6098, -1.1893,  1.1677]],

         [[ 0.3277, -0

## nn.Sequential

In [11]:
model = nn.Sequential(nn.Linear(3, 4), nn.Tanh(), nn.Linear(4, 5), nn.LogSoftmax(dim=1))
print("model:", model)
print("---" * 3)

# for p in model.parameters():
for p in model.named_parameters():
    print("p:", p)

print("---" * 3)

# print("model.weight:", model.weight)
# print("model.weight.shape:", model.weight.shape)
# print("model.weight.numel:", model.weight.numel())
# print("model.weight.dtype:", model.weight.dtype)
# print("model.weight.device:", model.weight.device)

# print("model.bias:", model.bias)
# print("model.bias.shape:", model.bias.shape)
# print("model.bias.numel:", model.bias.numel())
# print("model.bias.dtype:", model.bias.dtype)
# print("model.bias.device:", model.bias.device)

model: Sequential(
  (0): Linear(in_features=3, out_features=4, bias=True)
  (1): Tanh()
  (2): Linear(in_features=4, out_features=5, bias=True)
  (3): LogSoftmax(dim=1)
)
---------
p: ('0.weight', Parameter containing:
tensor([[-0.0035, -0.1671, -0.2799],
        [ 0.2709, -0.0503, -0.1144],
        [ 0.4011, -0.4384,  0.3770],
        [ 0.5128, -0.3547, -0.5470]], requires_grad=True))
p: ('0.bias', Parameter containing:
tensor([ 0.0803, -0.4391,  0.2414, -0.4605], requires_grad=True))
p: ('2.weight', Parameter containing:
tensor([[-0.3902,  0.1353, -0.1281, -0.4426],
        [ 0.1951,  0.1766,  0.0674,  0.3267],
        [-0.2007,  0.4564, -0.3811,  0.4508],
        [ 0.3715, -0.4448, -0.0444, -0.2690],
        [ 0.4920, -0.0209,  0.2945,  0.4323]], requires_grad=True))
p: ('2.bias', Parameter containing:
tensor([-0.3856,  0.3039, -0.4349, -0.1350, -0.2016], requires_grad=True))
---------


In [12]:
input = torch.randn(2, 3)
print("input:", input)
print("input.shape:", input.shape)

input: tensor([[-0.0311,  0.5558,  0.0690],
        [-0.7339,  1.9603,  0.4981]])
input.shape: torch.Size([2, 3])


In [13]:
output = model(input)
print("output:", input)
print("output.shape:", output.shape)

output: tensor([[-0.0311,  0.5558,  0.0690],
        [-0.7339,  1.9603,  0.4981]])
output.shape: torch.Size([2, 5])


## n.Module

In [14]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(6, 8, kernel_size=2)
        self.act1 = nn.Tanh()
        self.fc1 = nn.Linear(72, 32)
        self.act2 = nn.Tanh()
        self.fc2 = nn.Linear(32, 2)

    def forward(self, x):
        out = self.conv1(x)
        out = self.act1(out)  # torch.Size([2, 8, 3, 3])
        out = out.view(out.shape[0], -1)
        out = self.fc1(out)
        out = self.act2(out)
        out = self.fc2(out)

        return out

In [15]:
model = Net()
print("model:", model)
print("---" * 3)

# for p in model.parameters():
for p in model.named_parameters():
    print("p:", p)

print("---" * 3)

# print("model.weight:", model.weight)
# print("model.weight.shape:", model.weight.shape)
# print("model.weight.numel:", model.weight.numel())
# print("model.weight.dtype:", model.weight.dtype)
# print("model.weight.device:", model.weight.device)

# print("model.bias:", model.bias)
# print("model.bias.shape:", model.bias.shape)
# print("model.bias.numel:", model.bias.numel())
# print("model.bias.dtype:", model.bias.dtype)
# print("model.bias.device:", model.bias.device)

model: Net(
  (conv1): Conv2d(6, 8, kernel_size=(2, 2), stride=(1, 1))
  (act1): Tanh()
  (fc1): Linear(in_features=72, out_features=32, bias=True)
  (act2): Tanh()
  (fc2): Linear(in_features=32, out_features=2, bias=True)
)
---------
p: ('conv1.weight', Parameter containing:
tensor([[[[-0.1004, -0.1847],
          [ 0.1098,  0.1395]],

         [[ 0.0179, -0.1026],
          [-0.0495,  0.0119]],

         [[ 0.0855,  0.0035],
          [-0.0952,  0.0099]],

         [[ 0.0063,  0.0019],
          [ 0.0888, -0.0769]],

         [[ 0.0129,  0.0009],
          [ 0.0862, -0.1250]],

         [[-0.1596, -0.1661],
          [ 0.0858,  0.1624]]],


        [[[ 0.2025,  0.0729],
          [-0.0416,  0.0376]],

         [[-0.2019,  0.0236],
          [-0.0674, -0.0155]],

         [[ 0.1172, -0.0703],
          [-0.1546,  0.0123]],

         [[-0.0568, -0.0952],
          [-0.0624, -0.1157]],

         [[ 0.1792,  0.0140],
          [-0.1083,  0.1301]],

         [[ 0.0316,  0.1172],
        

In [16]:
input = torch.randn(2, 6, 4, 4)
# print("input:", input)
print("input.shape:", input.shape)

input.shape: torch.Size([2, 6, 4, 4])


In [17]:
output = model(input)
# print("output:", input)
print("output.shape:", output.shape)

output.shape: torch.Size([2, 2])
